### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by carpnick** [aws-solutions/cost-optimizer-for-amazon-workspaces#20]
Please add Cloudwatch monitoring to the Lambda/ECS as necessary and an SNSTopic to forward email to.  I checked in on this solution that we had deployed and found a Service Control Policy caused the lambda function to fail to kick off a new Task.  If there was monitoring on lambda invocations that forwarded to an email address, this would have been noticed much sooner.  So general monitoring of some kind to validate the solution is working correctly even at the basic level would be appreciated

**Comment by rakshb** [comment]
Hi @carpnick thanks for the request. We will add this to the backlog and review in a future release. What level of monitoring are you expecting? Is it only to check if Lambda invocations are occurring correctly or any other details about the invocations?

**Comment by carpnick** [comment]
I think any part of the solution that could fail to run where the customer thinks its running properly.  So just a pass/fail to alert the customer to look into it.

- Lambda invocations failing
- Container execution fails with a bad exit code

**Comment by rakshb** [comment]
We reviewed the request and do not have plans to build this in the immediate roadmap.
