### ISSUE TITLE
Terminate unused WorkSpaces issue

### ISSUE THREAD

**Issue by k4n30** [aws-solutions/cost-optimizer-for-amazon-workspaces#29]
Hi,

I think there may be an issue in the logic used to determine if a WorkSpace has been used that month. This of course affects the "Terminate unused WorkSpaces" function. It seems as though if a WorkSpace has NEVER been logged onto (therefore has no "last known user connection timestamp"), but meets all the other criteria, the WorkSpace is not terminated as would be expected.

i.e. WorkSpace created October 15 (and never logged onto) - End of month checks result in non termination (due to not being available on Oct. 1st. November rolls around and user never logs on - End of month check should result in termination, but doesn't.

I had it occur last month (end of Oct.), and this month (end of Nov.) and the only thing I could put it down to is that the WorkSpaces that didn't terminate had not ever been logged onto, whereas the ones who had were terminated successfully.

I didn't have debug logging turned on, so am unable to investigate further, but thought you might be able to look into it before the end of next month (of which I won't be at work to review the logs until early next year anyway)

**Comment by deolank** [comment]
Thanks for your feedback. We have added this to our product backlog.

**Comment by k4n30** [comment]
Hi @deolank - has there been any progress on this?

**Comment by deolank** [comment]
We do not have a release date for this yet. I will update here once we do. Thanks.

**Comment by deolank** [comment]
This has been fixed in the latest release(v2.6.0) of the solution.
