### ISSUE TITLE
Update ECS task definition to meet AWS Foundational Security Best Practices

### ISSUE THREAD

**Issue by k4n30** [aws-solutions/cost-optimizer-for-amazon-workspaces#31]
**Is your feature request related to a problem? Please describe.**
[AWS Foundational Security Best Practice](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ecs-5) defines that ECS containers should be limited to read-only access to root file systems [ECS.5]. Currently, the WCO task definition fails this control.

**Describe the feature you'd like**
The WCO ECS Task definition be updated to reflect the AWS-FSBP ECS.5 control

**Additional context**
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html

**Comment by deolank** [comment]
This has been fixed in our the latest release(v2.6.0) of the solution.
