### ISSUE TITLE
Malformed Policy

### ISSUE THREAD

**Issue by thebigcosinus** [aws-solutions/cost-optimizer-for-amazon-workspaces#42]
Hi,

I try to deploy the Spoke Stack as my AWS Worskpaces is in a single account.

When I lanched the Cloud formation v2.5.1 ([workspaces-cost-optimizer-spoke.template](https://github.com/aws-solutions/workspaces-cost-optimizer/blob/main/deployment/workspaces-cost-optimizer-spoke.template))

Cloudformation cannot deploy the stack I got the following erros:

**WorkSpacesManagementRole**

`Invalid principal in policy: "AWS":"arn:aws:iam::XXXXXXX:role/Workspaces-Cost-Optimizer-eu-west-1" (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 6a2be265-1730-4123-9526-efb113265067; Proxy: null)`

**AppRegistryApplicationStackAssociation**

`Resource handler returned message: "Application workspaces-cost-optimizer-eu-west-1-XXXXXXnot found (Service: ServiceCatalogAppRegistry, Status Code: 404, Request ID: d9c85cf6-c645-4551-a781-33ce9495bc06)" (RequestToken: fb33d613-4730-e10c-ca96-78878136df4e, HandlerErrorCode: NotFound)`

Can you help me with that please ?

Regards

**Comment by deolank** [comment]
For single account deployments, you do not need to deploy spoke template. Just deploy the hub template and it will manage the workspaces in that account.
