### ISSUE TITLE
Idle workspaces

### ISSUE THREAD

**Issue by sjegannath** [aws-solutions/cost-optimizer-for-amazon-workspaces#45]
**Is your feature request related to a problem? Please describe.**
Does this solution identify workspaces where users have not connected for a long time.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/workspaces/client/describe_workspaces_connection_status.html

**Describe the feature you'd like**
I would like a feature to identify workspaces where users have not connected for a long time and provide a mechanism to delete it.

**Additional context**

**Comment by deolank** [comment]
The solution has a feature to terminate unused workspaces. You can find more information here. https://docs.aws.amazon.com/solutions/latest/cost-optimizer-for-workspaces/features-and-benefits.html
