### ISSUE TITLE
Report creation frequency seems random - does not create daily reports

### ISSUE THREAD

**Issue by EjectSteve** [aws-solutions/cost-optimizer-for-amazon-workspaces#47]
WCO is working and I see daily log files of the running events.  But in the report bucket, there's only reports generated every few days at most.  The environment has around 260 workspaces and the reports are otherwise accurate.  

Have tried running in production and clean lab environment.  Is the report frequency supposed to be daily or is there other criteria for triggering when a report is generated?  Stack is running in dry run mode.   v2.6.1 Thanks

**Comment by deolank** [comment]
Closing this issue here as this is being worked on internally by the support team.
