### ISSUE TITLE
Debug statement incorrectly references directories

### ISSUE THREAD

**Issue by dbarlett** [aws-solutions/cost-optimizer-for-amazon-workspaces#58]
In [get_workspaces_for_directory](https://github.com/aws-solutions/cost-optimizer-for-amazon-workspaces/blob/df2d2db4d7e195f79d4a8796042eec687ee7155e/source/workspaces_app/workspaces_app/workspaces_helper.py#L164), `log.debug(f'Returning the list of directories as {list_workspaces}')` should be `log.debug(f'Returning the list of WorkSpaces as {list_workspaces}').`

**Comment by deolank** [comment]
Thanks for your feedback. We will fix this in the next release for the solution.

**Comment by deolank** [comment]
This was resolved in the latest release v2.6.4
