### ISSUE TITLE
GRAPHICS_G4DN not included in the tool

### ISSUE THREAD

**Issue by etiennejeanneaurevolve** [aws-solutions/cost-optimizer-for-amazon-workspaces#63]
**Describe the bug**

GRAPHICS_G4DN Workspaces are reported as "Skipped" in the CSV report.

**To Reproduce**

Create an ALWAYS_ON Workspace with compute type GRAPHICS_G4DN. Run WCO.

**Expected behavior**

I expected the GraphicsLimit variable in input to apply to GRAPHICS_G4DN workspaces.

**Please complete the following information about the solution:**

- [2.6.3 ] 
- [eu-west-1]
- [yes, only the networking part of the CFN template] Was the solution modified from the version published on this repository?
- [no ] If the answer to the previous question was yes, are the changes available on GitHub?
- no logging available around the function  WorkspacesHelper.get_hourly_threshold_for_bundle_type

I believe the list https://github.com/aws-solutions/cost-optimizer-for-amazon-workspaces/blob/main/source/workspaces_app/workspaces_app/directory_reader.py#L37 needs to be updated

**Comment by deolank** [comment]
This Workspace bundle is currently not supported for monitoring by the solution. We will include this support in the next release of the solution.

**Comment by edmoranmd** [comment]
Is there an update to when the graphics.g4dn will be supported?

**Comment by G-Lenz** [comment]
This feature has been added in v2.7.0 which released today (July 30, 2024)
