### ISSUE TITLE
Customer accidently deleted Security Group manually.

### ISSUE THREAD

**Issue by jacido** [aws-solutions/cost-optimizer-for-amazon-workspaces#68]
Hi Team, a customer accidently deleted the mentioned resource manually from the solution here[1].

The AWS::EC2::SecurityGroup SecurityGroupIngress resource was manually deleted and during our call I was able to reproduce the error.

We observed while attempting to recreate the resource and update the stack it resulting in resources being deleted and the stack going into either an UPDATE_ROLLBACK_COMPLETE or remain stuck in a UPDATE_COMPLETE_CLEANUP_IN_PROGRESS state.

In another test stack deployment we were able to observe a successful stack update resource recreation using the following properties below. When I had deleted the SecurityGroup resource referenced in the template I was able to successfully replace the resource with the use of resource tags[2] and ref[3] which did not replace the subnet, VPC or other resources. 

Eg:
----------
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Description": "HTTPS - Security Group for Route53 Health - https checks",
	"Parameters": {
		"VPC": {
			"Type": "AWS::EC2::VPC::Id",
			"Description": "VPC where the Security Group will belong"
		},
		"Name": {
			"Type": "String",
			"Description": "Name Tag of the Security Group"
		},
		"Description": {
			"Type": "String",
			"Description": "Description Tag of the Security Group"
		}
	},
	"Resources": {
		"Route53SG": {
			"Type": "AWS::EC2::SecurityGroup",
			"Properties": {
				"GroupDescription": {
					"Ref": "Description"
				},
				"VpcId": {
					"Ref": "VPC"
				},
				"SecurityGroupIngress": [
					{
						"IpProtocol": "tcp",
						"CidrIp": "54.183.255.128/26",
						"FromPort": "443",
						"ToPort": "443"

	"Outputs": {
		"SecurityGroupID": {
			"Description": "Security Group ID",
			"Value": {
				"Ref": "Route53SG"
----------

Requested fix:
Be able to successfully replace the Security Group and guidance on replacing accidently deleted resources.

References:
[1] - Cost Optimizer for Amazon WorkSpaces
https://aws.amazon.com/solutions/implementations/cost-optimizer-for-amazon-workspaces/

[2] - Resource tag
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

[3] - Ref
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html

**Comment by shujacks** [comment]
We are taking a look and will respond shortly.

**Comment by G-Lenz** [comment]
Hi, This is the nature of cloudformation, when the stack diverges and resources are modified/deleted outside of the stack, cloudformation can no longer reconcile the diff and is not able to update. While there is not a direct fix we would implement into the solution, we may be able to provide guidance in the implementation guide on how to do so. We will add the guidance update to our backlog.

**Comment by G-Lenz** [comment]
There is also some more information on updating a stack with manually deleted resources here: https://repost.aws/knowledge-center/failing-stack-updates-deleted
