### ISSUE TITLE
Support TagKey for running mode change exclusions

### ISSUE THREAD

**Issue by hiroinfinity** [aws-solutions/cost-optimizer-for-amazon-workspaces#74]
**Is your feature request related to a problem? Please describe.**

When the running mode of Workspaces is AutoStop, we have users who cannot wait for the startup time and want to exclude them from the automatic changes of this solution.

**Describe the feature you'd like**

I would like to add the ability to give Workspaces a specific tag to exclude changes.

**Additional context**

**Comment by sanjay-reddy-kandi** [comment]
Hi, Please can you look at this [Opt out WorkSpaces](https://docs.aws.amazon.com/solutions/latest/cost-optimizer-for-workspaces/features-and-benefits.html#opt-out-workspaces) feature in our Implementation guide and let us know if this what you are looking for?

**Comment by hiroinfinity** [comment]
@sanjay-reddy-kandi 
Thank you.
That is the feature I wanted.
