### ISSUE TITLE
The following resource(s) failed to create: [UUIDGenerator].

### ISSUE THREAD

**Issue by salagula** [aws-solutions/cost-optimizer-for-amazon-workspaces#77]
Since the update to 2.7.x the solution is not working anymore. It always points to the UUIDgenerator - neither uninstall, nor reinstallation does work. In both cases the deletion/creation of UUIgenerator is stuck

After some minutes also the rollback does not work

![image](https://github.com/user-attachments/assets/9110dae0-b9d2-4e61-8d72-3784bd345e2a)

CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [d3ab99d1-a355-43c2-8337-ba247c9bba10]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.

**Comment by sanjay-reddy-kandi** [comment]
Hello,

Thank you for reporting this issue. To help us investigate and reproduce the problem, could you please provide the following information:

- During which deployment process did the error occur? Create/update or delete the solution stack?
- Whether you attempted to manually update the solution before the error occurred.
- The specific version of 2.7.x you are currently using.
- The status of your Auto-update Container Image setting (true or false).

**Comment by salagula** [comment]
Hi - issue was fixed by providing the full URL (https://solutions-reference.s3.amazonaws.com/cost-optimizer-for-amazon-workspaces/latest/cost-optimizer-for-amazon-workspaces.template) - instead of downloaded json
